### ISSUE TITLE
Introduce/enable a rule for trailing commas in rubocop

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-fastlane-plugin#105]
We should discuss if we wanna use trailing commas and enable the rule we land on in `rubocop`.

I'm more in the no trailing commas camp, but I think we should discuss this before starting a PR.

Some quick google searches yielded:
https://github.com/rubocop/ruby-style-guide/issues/273
https://rubystyle.guide/#no-trailing-parameters-comma
https://rubystyle.guide/#no-trailing-params-comma

**Comment by philipphofmann** [comment]
Sure that sounds reasonable. Are you up for a PR @denrase?

**Comment by denrase** [comment]
Sure! Do you or anyone from your team have an opinion on this?

**Comment by philipphofmann** [comment]
I'm not an expert on Ruby. Maybe it's worth checking out what we do here https://github.com/getsentry/sentry-ruby ?

**Comment by philipphofmann** [comment]
This was fixed with #121
