### ISSUE TITLE
Issue using the plugin to upload symbols

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-fastlane-plugin#110]
Users have reported not being successful following the guide from the docs:

https://docs.sentry.io/platforms/apple/guides/ios/dsym/#bitcode-fastlane

@brustolin wasn't successful on his first try with it either. This issue is here for us to revisit the flow of docs -> plugin to make sure the first experience with this is positive

**Comment by kahest** [comment]
bitecode has been deprecated and the according docs have been adapted: https://docs.sentry.io/platforms/apple/guides/ios/dsym/#dsym-with-bitcode
