### ISSUE TITLE
Update sentry-cli

### ISSUE THREAD

**Issue by qvaleroo** [getsentry/sentry-fastlane-plugin#112]
### I have updated my plugin from 1.10.1 to 1.11.1 and now I have this error in my CI:

`ERROR [2022-02-18 08:05:39.51]: Your sentry-cli is outdated, please upgrade to at least version 1.72.0 and start your lane again!
`

How can I update my sentry-cli in my plugin ? Can't find it

**Comment by qvaleroo** [comment]
I think there is a cache in my CI using the old Sentry-cli, closing question

**Comment by fccoelho7** [comment]
I can't find it too. I already got the CLI installed via Homebrew but the process can't find it.
