### ISSUE TITLE
Add `gem install fastlane-plugin-sentry` to Getting Started section of README

### ISSUE THREAD

**Issue by macblazer** [getsentry/sentry-fastlane-plugin#114]
As a new user trying to use this plugin with fastlane, a missing piece of information is that I need to install the gem in one of two ways:

- Using `gem install fastlane-plugin-sentry` and then I can use it with any project globally with the simple `fastlane...` command.

- Using `bundle install` in a project folder that uses fastlane with either a Gemfile that specifies the plugin, or possibly after running the `fastlane add_plugin sentry` command that is listed in the README.  And then I need to use `bundle exec fastlane...` to run fastlane with the plugin.

Either way, there is a little bit of missing information that could be added to the top of the README to make this easier to adopt.

**Comment by Mordil** [comment]
Documentation also needs to specify that the CLI needs to be installed on the machine & won't be done by default by the fastlane plugin
