### ISSUE TITLE
The plugin does not support the latest version of Sentry CLI

### ISSUE THREAD

**Issue by adhumi** [getsentry/sentry-fastlane-plugin#117]
### Environment

Sentry SaaS
CLI 2.0.1
Fatlane plugin 1.11.1

### Steps to Reproduce
Try to upload symbols using the fastlane plugin, with Sentry CLI >2.0 installed

### Actual Result
The upload fails with the following message:

```
[15:06:27]: Starting sentry-cli...
[15:06:27]: error: The subcommand 'upload-dsym' wasn't recognized
```

**Comment by leezumstein** [comment]
I opened #119 to fix this, not sure how to get attention from the maintainers for review.

**Comment by philipphofmann** [comment]
We are going to fix this with the next sentry-cli update, see https://github.com/getsentry/sentry-fastlane-plugin/pull/119#issuecomment-1097688039. sentry-cli is going to be backwards compatible and no changes are needed for sentry-fastlane-plugin right now.
