### ISSUE TITLE
error: The subcommand 'upload-dsym' wasn't recognized

### ISSUE THREAD

**Issue by leezumstein** [getsentry/sentry-fastlane-plugin#118]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
React Native 0.66.2, @sentry/react-native 3.2.12
macOS 12.13, Fastlane 2.205.1, fastlane-plugin-sentry 1.11.1

### Steps to Reproduce

1. Install `sentry-cli` tool using Homebrew:
   ```bash
   brew install getsentry/tools/sentry-cli
   ```
   - _At time of writing this bug, was pulling version 2.0.1_
1. Running a custom lane with the following:
   ```ruby
   # Download the latest symbols from App Store Connect
   download_dsyms(
     username: ENV["FASTLANE_APPLE_ID"],
     app_identifier: "<our app identifier>",
     team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
     version: "<our latest app version>",
     build_number: "<our latest app build code>",
     output_directory: "<some output directory>",
     wait_for_dsym_processing: true,
     wait_timeout: 60 * 12 # wait up to 12 minutes for processing to complete
   )

   # Upload symbols to Sentry
   sentry_upload_dsym(
     dsym_paths: lane_context[SharedValues::DSYM_PATHS],
     symbol_maps: "<path to our BCSymbolMaps directory>",
     info_plist: '<path to our plist>'
   )
   ```

### Expected Result

Would have expected our dSYMs to be uploaded to sentry.  It looks like there was some breaking change released with the new `sentry-cli` that this fastlane plugin isn't handling.

### Actual Result

Receiving the following error when executing `sentry_upload_dsym`
 ```bash
 [10:03:54]: --------------------------------
 [10:03:54]: --- Step: sentry_upload_dsym ---
 [10:03:54]: --------------------------------
 [10:03:55]: sentry-cli 2.0.1 installed!
 [10:03:55]: Starting sentry-cli...
 [10:03:55]: error: The subcommand 'upload-dsym' wasn't recognized
 [10:03:55]: If you believe you received this message in error, try re-running with 'sentry-cli -- upload-dsym'
 [10:03:55]: Error while calling Sentry CLI
 ```

**Comment by leezumstein** [comment]
It's worth mentioning we tried exploring options of installing the previous `sentry-cli` version before the `2.x.x` release, but homebrew doesn't offer any ways of performing this step AFAIK.

Is there possibly a way to install a specific version of this tool to avoid the breaking changes until this plugin can be updated?

**Comment by kamilogorek** [comment]
Everything should be working back again in `2.0.2`, thanks for your patience.
