### ISSUE TITLE
Support for sentry-cli 2.0.1

### ISSUE THREAD

**Issue by pskow** [getsentry/sentry-fastlane-plugin#120]
Hello!
When can we expect support for sentry-cli 2.0.1?

**Comment by mokagio** [comment]
This is a duplicated of #117. Also, there's a PR, currently not yet merged, #119, that addresses this issue.

**Comment by philipphofmann** [comment]
Yes, this is a duplicate of https://github.com/getsentry/sentry-fastlane-plugin/issues/117.
