### ISSUE TITLE
sentry_upload_dsym was fast, sentry_upload_dif taking over 10 minutes.

### ISSUE THREAD

**Issue by BDProject** [getsentry/sentry-fastlane-plugin#122]
### Environment

How do you use Sentry?
Sentry SaaS 

Which SDK and version?
Sentry_CLI 2.x Running Fastlane/CircleCI
### Steps to Reproduce
We changed our Fastlane script from using the below in 1.74.3
sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG_SLUG'],
       project_slug: ENV['SENTRY_PROJECT_SLUG']
     )
Which was taking 10seconds to finish.

To the below in 2.0.x
sentry_upload_dif(
   	auth_token: ENV['SENTRY_AUTH_TOKEN'],
   	org_slug: ENV['SENTRY_ORG_SLUG'],
   	project_slug: ENV['SENTRY_PROJECT_SLUG']
       )
Which is taking 620+ seconds to run before causing CircleCI to stop the script.

### Expected Result
It would execute quickly as in 1.74.3

### Actual Result
In 2.0.x having moved to sentry_upload_dif it is taking too long. 

Can you advise if there is an issue in how we use the new function or what would you suggest.

I would appreciate any support or feedback you can offer.

**Comment by BDProject** [comment]
Looking through other issues, could we revert back to using the old command sentry_upload_dsym instead of sentry_upload_dif?

**Comment by philipphofmann** [comment]
@kamilogorek, do you have any clue what inside sentry-cli could cause this?

@BDProject, can you please check the logs of how many debug symbol files `sentry_upload_dif` finds and uploads to Sentry?

**Comment by BDProject** [comment]
@philipphofmann we reverted back to using sentry_upload_dsym and everything is working again. I'd suggest if you diff the 2 methods it might be apparent what could cause the issue for one, but not the other.

**Comment by kamilogorek** [comment]
You reverted to `sentry_upload_dsym`, while still using v2? If so, those are the same commands now.

**Comment by BDProject** [comment]
@kamilogorek, that is strange then how reverting that 1 change made it instantly succeed.

**Comment by kamilogorek** [comment]
Agree. They are 1:1 the same code 😅

https://github.com/getsentry/sentry-cli/blob/master/src/commands/upload_dsym.rs
https://github.com/getsentry/sentry-cli/blob/master/src/commands/upload_dif.rs

**Comment by BDProject** [comment]
I guess this issue can be closed :) Thanks for all the input everybody.
