### ISSUE TITLE
CI to run and bump the sentry-cli automatically and run tests

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-fastlane-plugin#126]
"Dependabot, but for Sentry CLI":

The CI could bump sentry-cli to the latest version and see if there are any issues.
Ideally the trigger is defined by a release on sentry-cli. Please make sure it includes previews (the main goal)
Triggering from here [might not be possible](https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release), but we could setup the action on the sentry-cli repo to trigger a workflow here that [creates a PR with the change](https://github.com/getsentry/sentry-unity/blob/1db2fa4fa6fd067e907ae6d2306a3ce24d0b9d34/.github/workflows/update-deps.yml#L50-L61).

Ideally this setup will work also for other plugins such as:

* https://github.com/getsentry/sentry-dart-plugin/blob/main/download-sentry-cli.sh
* https://github.com/getsentry/sentry-android-gradle-plugin

**Comment by denrase** [comment]
@bruno-garcia I'm in the process to figure this out. Here's what i have so far:

- This repo does not bundle `sentry-cli` but uses the one installed on the host system, but we can provide a pram with a custom path.
- I wrote a script (locally) that fetches the latest version from the `sentry-cli` repo and downloads it to a subfolder.
- We could run this scheduled with an action (cron). Not super cool, as we are polling the whole time, but we can stay in the scope of this repo (for now).

So far so good, now we have the most recent version in our hands and could proceed. The main questions is now, what do we mean by `see if there are any issues` and what should we actually test? Are there any end-to-end tests we can run using the plugin in tandem with the most recent `sentry-cli`?

**Comment by philipphofmann** [comment]
Thanks for looking into this, @denrase.

> I wrote a script (locally) that fetches the latest version from the sentry-cli repo and downloads it to a subfolder.

Can you maybe share the script here in the issue, so it doesn't get lost?

> We could run this scheduled with an action (cron). Not super cool, as we are polling the whole time, but we can stay in the scope of this repo (for now).

Once per day should be okay.

> what should we actually test

I would say this is the most important use case https://github.com/getsentry/sentry-fastlane-plugin/pull/128

> Assuming we know how to test, we could then open a bugfix PR which has the error message in the description.

I don't fully understand this. A bugfix PR with which error description?

**Comment by brustolin** [comment]
Hi @denrase. Is this already done? 
If so, close this please with a reference to the PR.

Thanks!!

**Comment by denrase** [comment]
@brustolin Yea, done in https://github.com/getsentry/sentry-fastlane-plugin/pull/144. Sry for the delay!
