### ISSUE TITLE
Execution freezes if fastlane was started with verbose flag

### ISSUE THREAD

**Issue by vandyshev** [getsentry/sentry-fastlane-plugin#129]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
fastlane (2.206.2)
fastlane-plugin-sentry (1.12.0)

### Steps to Reproduce

Run fastlane lane with **--verbose**

### Expected Result
Plugin completes correctly
```
[17:28:18]: -------------------------------
[17:28:18]: --- Step: sentry_upload_dif ---
[17:28:18]: -------------------------------
[17:28:18]: sentry-cli 2.2.0 installed!
[17:28:18]: Starting sentry-cli...
[17:28:22]: > Found 124 debug information files
[17:28:22]: > Warning: Found 4 symbol files with hidden symbols (need BCSymbolMaps)
[17:28:23]: > Prepared debug information files for upload
[17:28:24]: > Nothing to upload, all files are on the server
[17:28:24]: > No new debug symbols to associate.
[17:28:24]: Successfully ran upload-dif
```

### Actual Result
Plugin freezes after Prepared debug information files for upload

```
INFO [2022-06-22 17:23:09.73]: -------------------------------
INFO [2022-06-22 17:23:09.73]: --- Step: sentry_upload_dif ---
INFO [2022-06-22 17:23:09.73]: -------------------------------
INFO [2022-06-22 17:23:09.76]: sentry-cli 2.2.0 installed!
INFO [2022-06-22 17:23:09.76]: Starting sentry-cli...
DEBUG [2022-06-22 17:23:09.76]: sentry-cli command:


INFO [2022-06-22 17:23:09.76]: $ ["/usr/local/bin/sentry-cli", "upload-dif", "./output"]
DEBUG [2022-06-22 17:23:09.76]:


INFO [2022-06-22 17:23:14.72]: > Found 124 debug information files
INFO [2022-06-22 17:23:14.75]: > Warning: Found 4 symbol files with hidden symbols (need BCSymbolMaps)
INFO [2022-06-22 17:23:14.90]: > Prepared debug information files for upload
```

**Comment by philipphofmann** [comment]
Thanks, @vandyshev, for reporting this issue. I just tried this locally myself and it also froze for a couple of seconds after calling sentry-cli and then it gets stuck as well at `Prepared debug information files for upload`. It seems like `sentry-cli` somehow gets stuck.

@kamilogorek, do you maybe know why sentry-cli could get stuck when setting `ENV['SENTRY_LOG_LEVEL'] = 'DEBUG'`?

We set the env variable here
https://github.com/getsentry/sentry-fastlane-plugin/blob/ad5b786ec630a86195e9f70f0f5e43dfe2b44e20/lib/fastlane/plugin/sentry/helper/sentry_config.rb#L57

And then call sentry-cli here 
https://github.com/getsentry/sentry-fastlane-plugin/blob/ad5b786ec630a86195e9f70f0f5e43dfe2b44e20/lib/fastlane/plugin/sentry/helper/sentry_helper.rb#L28-L55

**Comment by kamilogorek** [comment]
I cannot reproduce it locally.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1523305/175970465-ac92e4a7-c454-4201-9cf1-a1264222864a.png">
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1523305/175970501-201c1991-f1bb-407e-876d-a5f291083366.png">

**Comment by philipphofmann** [comment]
Maybe this helps:

1. Check out sentry-cocoa
2. build the iOS-Swift sample project with Xcode
3. Apply the patch below 
4. Run `fastlane upload_dif --verbose`

```
diff --git a/fastlane/Fastfile b/fastlane/Fastfile
index e541f697..51527037 100644
--- a/fastlane/Fastfile
+++ b/fastlane/Fastfile
@@ -144,6 +144,15 @@ platform :ios do
     )
   end
 
+  lane :upload_dif do
+    sentry_upload_dif(
+      auth_token: ENV["SENTRY_AUTH_TOKEN"],
+      org_slug: 'sentry-sdks',
+      project_slug: 'sentry-cocoa',
+      symbol_maps: 'iOS-Swift.xcarchive/BCSymbolMaps/'
+    )
+  end
+
   lane :ui_tests_ios_swiftui do
     run_tests(
       workspace: "Sentry.xcworkspace",

```

**Comment by kamilogorek** [comment]
Still cannot reproduce it locally despite following repro steps :(

**Comment by philipphofmann** [comment]
Maybe this helps, @kamilogorek?
```
➜ which sentry-cli
/usr/local/bin/sentry-cli

➜ sentry-cli --version
sentry-cli 2.0.2
```

Updating to sentry-cli 2.2.0 didn't help.
