### ISSUE TITLE
Regression in `call_sentry_cli`: no return value

### ISSUE THREAD

**Issue by lhunath** [getsentry/sentry-fastlane-plugin#139]
Regression from: 68308375fb6fe4938376c8ee0f0a733e6de0c4b6

`SentryHelper.call_sentry_cli` appears to no longer return its output as a return value.

Most uses of this utility do not care about the return value, but `fallback_sentry_cli_auth` does, since it uses it to parse the sentry config status.

This now fails since the return value is `nil`:
```
ERROR [2022-07-05 11:25:39.31]: no implicit conversion of nil into String
```

**Comment by philipphofmann** [comment]
Thanks for reporting this, @lhunath. @kamilogorek, could you have a look, please?

**Comment by lhunath** [comment]
Please bump the release; the broken .1 release is a blocker for me.
