### ISSUE TITLE
Allow passing multiple files to sentry_upload_sourcemap

### ISSUE THREAD

**Issue by acaldas** [getsentry/sentry-fastlane-plugin#141]
When using Hermes on Android the sourcemap has to be uploaded with the bundle or Sentry won't display the stack trace correctly.

Uploading the bundle in a separate action produces a warning:

<img width="1125" alt="Sourcemap log" src="https://user-images.githubusercontent.com/5501872/177562442-8a527616-ae44-402f-af31-3e72ed9d2030.png">

And the error show on Sentry:
![Sentry error](https://user-images.githubusercontent.com/5501872/177562668-22f58a97-47de-43fa-a516-5bfd7a1b47ce.png)

According to this [Issue from sentry-react-native](https://github.com/getsentry/sentry-react-native/issues/2244#issuecomment-1155735936), I tried uploading both files using `sentri-cli` directly and the stack trace is shown correctly:
`sentry-cli releases files $release upload-sourcemaps --dist $dist --strip-prefix ... --rewrite android/app/build/generated/assets/react/release/index.android.bundle android/app/build/generated/sourcemaps/react/release/index.android.bundle.map`

<img width="618" alt="Captura de ecrã 2022-07-06, às 10 51 25" src="https://user-images.githubusercontent.com/5501872/177562838-c207d2ba-241f-4c19-9f9e-015896d09e55.png">

Looking at [the code](https://github.com/getsentry/sentry-fastlane-plugin/blob/369affccf9e6570cb52275d1c0dfb7e016fe6cb8/lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb#L84), if the `sentry_upload_sourcemap` didn't check if the given file exists, we could just pass a string with both filepaths separated with a whitespace and the generated command would work.

**Comment by acaldas** [comment]
> Thanks for reporting this, @acaldas. So you currently have a workaround with using sentry-cli directly, right? Anyways we should fix `sentry_upload_sourcemap` to support your use case.

Yeah, passing both files to the sentry-cli command works. Would be great if the fastlane plugin supported this!

**Comment by denrase** [comment]
This is beeing worked on in #151
