### ISSUE TITLE
Will 1.13.0 be released soon (for bundled iOS sentry-cli)?

### ISSUE THREAD

**Issue by matt-dalton** [getsentry/sentry-fastlane-plugin#159]
In the [readme it says](https://github.com/getsentry/sentry-fastlane-plugin#specify-custom-sentry-cli-path) we get the Sentry CLI bundled with the plugin for macOS builds, but it looks like this hasn't been released. Would this be easy to release? It would be great to not have to install the CLI separately.

**Comment by brustolin** [comment]
Hello @matt-dalton, this is going to be release today :D

**Comment by brustolin** [comment]
@denrase Do you know if this is already the case? Can we bump the version?

**Comment by matt-dalton** [comment]
Would be amazing if this was an easy fix. I think there are quite a few issues around CI systems not picking up the correct Sentry CLI, so I'm hoping this would resolve those. One such issues is currently blocking our migration to fastlane for example.

**Comment by denrase** [comment]
@brustolin AFAIK there are no blockers and we could make a release. Maybe @bruno-garcia has something to add?

**Comment by iBotPeaches** [comment]
I think it would be swell if you could squeeze https://github.com/getsentry/sentry-fastlane-plugin/pull/151 in and cut 1.13.0. Been waiting on that one to fix our hermes sourcemap builds.

**Comment by matt-dalton** [comment]
> Been waiting on that one to fix our hermes sourcemap builds.

Ah...potentially that's one of the other issues we're having!

**Comment by denrase** [comment]
@philipphofmann AFAIK you did the last couple of releases. Is there anything blocking us? Also with #151?

**Comment by philipphofmann** [comment]
No, will have a look soon. I hope we can release today.

**Comment by philipphofmann** [comment]
Closed with https://github.com/getsentry/publish/issues/1326.
