### ISSUE TITLE
upload_dif action cannot take list of paths

### ISSUE THREAD

**Issue by tmm1** [getsentry/sentry-fastlane-plugin#162]
The cli can take multiple paths but the fastlane action will only accept one.

The cli nor action let you ignore certain paths, so the default of `.` is breaking for me because of random zip files inside `vendor/gems`

**Comment by philipphofmann** [comment]
Thanks, @tmm1, for reporting this. @denrase, is this something you could look into?

**Comment by kamilogorek** [comment]
You can use `no-zips` to explicitly skip `zip` files. Unless there are some that you still want to include?
