### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wayneYo** [getsentry/sentry-fastlane-plugin#163]
### Environment

1.1.30

### Actual Result

After I upgraded the plugin to 1.13.0, I got an error when I ran SENTRY_UPLOAD_DSYM to upload the dsym

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/12230559/190980540-502b292f-94fa-455c-a5bd-006142a0e500.png">

**Comment by philipphofmann** [comment]
On which version did it work the last time @wayneYo? Which parameters do you pass to `sentry_upload_dsym`?

**Comment by Robert-F** [comment]
We experience the same issue after updating fastlane-plugin-sentry to `1.13.0` (and fastlane to version `2.210.0`).

We use `sentry_upload_dif`:
```
sentry_upload_dif(url: "[REDACTED]", auth_token: "[REDACTED]", org_slug: "[REDACTED]", project_slug: "[REDACTED]")
```

Downgrading to fastlane-plugin-sentry again to `1.12.2` resolved the problem for us for now.

**Comment by wayneYo** [comment]
> 上次在哪个版本上运行@wayneYo? 你传递给哪些参数`sentry_upload_dsym`？

sentry_upload_dsym(url: '', auth_token: '', org_slug: '' , project_slug: '')

**Comment by wayneYo** [comment]
> On which version did it work the last time @wayneYo? Which parameters do you pass to `sentry_upload_dsym`?

sentry_upload_dsym(url: '', auth_token: '', org_slug: '' , project_slug: '')

**Comment by denrase** [comment]
@philipphofmann Yes, will investigate!

**Comment by denrase** [comment]
Hey @wayneYo and @Robert-F, on which platform (macOS, windows, linux) and processor arch (32/64 bit) are you running fastlane?

**Comment by wayneYo** [comment]
@denrase  M1 processor, arm64, macOS Monterey 12.6。 I updated Fastlane to 2.210.1 and sentry-fastlane-plugin to 1.13.1, but the problem still exists。My Fastlane is installed through Homebrew, I wonder if this will help you troubleshoot the problem

**Comment by denrase** [comment]
Thank you both, this should help to pin down the issue! 🙇

**Comment by denrase** [comment]
Also running on M1 and both `sentry_upload_dsym ` and `sentry_upload_dif ` work for me.

@wayneYo & @gcazangi 

Could you check if the installed sentry fastlane plugin has the sentry-cli binary files? I also have fastlane installed with homebrew, on my machine the folder is `/opt/homebrew/lib/ruby/gems/3.1.0/gems` and the installed gems look like this:

<img width="408" alt="Bildschirmfoto 2022-09-28 um 10 31 53" src="https://user-images.githubusercontent.com/3984453/192731006-3019b959-e678-4e79-bd9a-b843a376acfb.png">

Also you could try to run the `sentry_cli_path` binary in there. It should point to the correct binary.

<img width="1145" alt="Bildschirmfoto 2022-09-28 um 10 36 54" src="https://user-images.githubusercontent.com/3984453/192731408-75ab9b6c-0d7d-4f87-afe1-43567beee4c5.png">

**Comment by wayneYo** [comment]
@denrase 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/12230559/192746374-43d356c7-5057-4058-94e0-5fe8dcb812ff.png">
<img width="553" alt="image" src="https://user-images.githubusercontent.com/12230559/192746691-098ef371-21ad-41f8-8cbf-f15bed6c17f3.png">

**Comment by wayneYo** [comment]
![image](https://user-images.githubusercontent.com/12230559/192748279-a95290a3-5901-463b-bc7e-0a2d65ee2e6f.png)
This is the complete error log after running the command

**Comment by denrase** [comment]
@wayneYo Thank you! All files are where they are supposed to be, but it seems that the file `sentry_cli_path` that we bundle is searched in the `libexec/bin` folder, instead of our own. How are you calling fastlane in the folder where you have your project setup? Globally with the `fastlane` comman, or with `bundle exec fastlane`? Does it make a difference?

**Comment by wayneYo** [comment]
@denrase   I should not have made this setting. I use the gym method to package and then the sentry_upload_dSYm method to upload the DSYM

**Comment by denrase** [comment]
@wayneYo Would you be so kind and try calling `bundle install` in your projects directory and then call `bundle exec fastlane`?

**Comment by wayneYo** [comment]
@denrase 
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/12230559/192917510-a85a703d-20aa-4485-b1c7-a3b44277f9d2.png">
I just added a shell script to the project so that the project could automatically upload DSYM after archiving. Does this matter ?
