### ISSUE TITLE
It is unclear how dysm uploads are associated with releases in Sentry for iOS

### ISSUE THREAD

**Issue by aslattum-addepar** [getsentry/sentry-fastlane-plugin#191]
I'm installing Sentry for the first time and have set an `environment` set as well as a `releaseName` set in the `SentrySDK.start` function in AppDelegate. When modifying my `Fastfile` to be able to upload dysms, it is unclear how those dysms will be reconciled with the correct version. There's no where in the Sentry docs that talk about this either. After some digging I found https://github.com/getsentry/sentry-fastlane-plugin/issues/84 which indirectly tells me that the fastlane plugin now uses `CFBundleIdentifier` + `CFBundleShortVersionString` + `CFBundleVersion`

My ask is should I just not specify a `releaseName` in my iOS app and let sentry link the dysms together?

**Comment by philipphofmann** [comment]
@aslattum-addepar, you don't need to associate dSYMs with specific releases. Every dSYM has a debug id like `91597a1b-deb4-3e53-8e24-8a1e4397f24d`. When sending an event to Sentry the stacktrace contains that debug id. Sentry then looks for all uploaded dSYMs to find the matching one and links them for you. 

When looking at an issue, you can scroll down to images loaded, expand the view and get more details on that.

<img width="1262" alt="Screenshot 2023-03-14 at 16 07 08" src="https://user-images.githubusercontent.com/2443292/225045125-fdddc076-3f6d-4749-ae56-6f4f971bd383.png">

<img width="1258" alt="Screenshot 2023-03-14 at 16 07 23" src="https://user-images.githubusercontent.com/2443292/225045180-bc324242-285c-4081-8c44-79a995b0ccd2.png">

Does this answer your question @aslattum-addepar?

**Comment by philipphofmann** [comment]
I think this question should be answered. Please reopen otherwise, @aslattum-addepar.
