### ISSUE TITLE
Setting include_sources:false should not upload SourceBundles

### ISSUE THREAD

**Issue by nickkaczmarek** [getsentry/sentry-fastlane-plugin#227]
### Environment

Fastlane plugin version: 1.16.0
Xcode 14.3

### Steps to Reproduce

1. Follow steps in the [sentry docs for uploading debug symbols](https://docs.sentry.io/platforms/apple/dsym/#fastlane)

2. Using the fastlane plugin with this snippet:

```ruby
sentry_upload_dif(
  auth_token: my_auth_token,
  org_slug: my_org_slug,
  project_slug: my_project_slug,
  include_sources: false,
)
```

3. Added `no_sources: true,` when I noticed symbols were being uploaded but the same result.

### Expected Result

I expected that no SourceBundles would be uploaded.

We have rules at my company about not uploading our source code to places that we don't control. I think SourceBundles are equivalent to source code being uploaded so I really don't want these uploaded.

> The resulting source bundle is an archive containing all source files referenced by a specific debug information file.

[Source](https://docs.sentry.io/product/cli/dif/#creating-source-bundles)

### Actual Result

When I go to the project in sentry then to Settings -> Debug Files I see this:

<img width="628" alt="Screenshot 2023-12-20 at 10 53 03" src="https://github.com/getsentry/sentry-fastlane-plugin/assets/9044401/7938f882-312b-450e-86df-39286950beb6">

### Further questions

- Am I using this tool wrong?
- Are SourceBundles not actual source code and we should feel safe to have them uploaded?
- Is there a way to upload dSYM files and exclude source code snippets?

**Comment by nickkaczmarek** [comment]
@kahest Ah okay that's good to know. So just to be clear, if I use `sentry_upload_dif` without `include_sources` or `no_sources` I should expect that no source bundles are uploaded?

**Comment by nickkaczmarek** [comment]
And to your point about documenting it more clearly

> When setting the include_sources parameter to true, the Fastlane plugin will scan your debug files to find references to the source code files, resolve them in the local file system, bundle them up, and upload them to Sentry.

This line seems to imply that setting that property will cause a change in behavior.

Maybe something like:

> When including the `include_sources` parameter, the Fastlane plugin will scan your debug files to find references to the source code files, resolve them in the local file system, bundle them up, and upload them to Sentry. Exclusion of this parameter will not upload source code files.

I can make an MR for the docs if you think this makes it clearer how this tool works.

**Comment by kahest** [comment]
@nickkaczmarek Correct - you need to omit `include_sources` to prevent source bundles from being uploaded. `no_sources` is used to determine whether the server supports source bundles, but this is overridden by `sentry-cli` retrieving a list of supported formats from the server, so it has no effect here.

Thank you for the wording suggestion, I think this would make it much clearer. We will discuss in which direction we'll go and follow up here.

**Comment by nickkaczmarek** [comment]
Thanks @kahest. Do you want me to keep this issue open? From my perspective I understand the behavior and my questions are answered, but not sure if you want to keep this open until a further docs/params change is made.

**Comment by kahest** [comment]
@nickkaczmarek yes let's keep it open for now - we'll split out separate issue(s) later

**Comment by philipphofmann** [comment]
> include_sources parameter is present - setting it to false currently doesn't deactivate this

I think if you set it to false, it should deactivate this. This would be a simple change.

**Comment by nickkaczmarek** [comment]
> > include_sources parameter is present - setting it to false currently doesn't deactivate this
> 
> I think if you set it to false, it should deactivate this. This would be a simple change.

This is what I thought would happen. I would guess I'm not alone in this. Also I think this makes more sense than updating the docs in the way I suggested above. False should not send the sources and true should send the sources.
