### ISSUE TITLE
"A required debug information file was missing" despite successful upload 

### ISSUE THREAD

**Issue by clemens-unterkofler** [getsentry/sentry-fastlane-plugin#230]
Output from build:

[15:54:43]: --------------------------------
[15:54:43]: --- Step: sentry_upload_dsym ---
[15:54:43]: --------------------------------
[15:54:43]: Using sentry-cli 2.21.2
[15:54:43]: Starting sentry-cli...
[15:54:50]: > Found 49 debug information files
[15:54:50]: > Prepared debug information files for upload
[15:54:57]: > Uploaded 43 missing debug information files
[15:54:58]: > File upload complete:
...
UPLOADED <redacted id> (<redacted app>.app.dSYM/Contents/Resources/DWARF/<redacted app>; arm64 debug companion)
...
[15:54:58]: > No new debug symbols to associate.
[15:54:58]: Successfully uploaded dSYMs!

But Sentry reports:
A required debug information file was missing (1)

File Name	<redacted app>
File Path		/private/var/containers/Bundle/Application/<redacted>/<redacted app>.app/
Debug ID		<redacted id, matches upload>

**Comment by philipphofmann** [comment]
@clemens-unterkofler, can you please provide more details on how you call the Fastlane plugin? Which parameters do you use, and do you call it locally or in CI?

**Comment by clemens-unterkofler** [comment]
Seems not to be a bug in the fastlane plugin. When I upload manually with sentry-cli I get the following:
`>Nothing to upload, all files are on the server
> No new debug symbols to associate.`

It seems to be a bug in sentry.io .

**Comment by philipphofmann** [comment]
So when you manually upload the debug symbols with sentry-cli, you still get the warning `A required debug information file was missing (1)`, @clemens-unterkofler? 

If yes, which debug file is missing? You can get that information by scrolling down in the issue to images loaded and check for an image marked as missing as pointed out in the screenshot: 
![CleanShot 2024-01-10 at 10 29 50](https://github.com/getsentry/sentry-fastlane-plugin/assets/2443292/6665e9ca-bae2-4116-9fc9-1b2995719084)

**Comment by clemens-unterkofler** [comment]
the issue seems to be the getting the wrong project slug from copying from the documentation:
https://docs.sentry.io/platforms/apple/guides/ios/dsym/#sentry-cli
