### ISSUE TITLE
Automate Sentry-cli bump

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-fastlane-plugin#240]
Can we somehow automate Sentry-cli bump instead of always approving and merging the bump CI?

**Comment by philipphofmann** [comment]
We still check in the binaries of the sentry-cli. So, adding every version increases the repo size quite a bit. I think, instead, we should only update it before we do a new release. For that having a script we can run manually would be enough.

**Comment by brustolin** [comment]
>I think, instead, we should only update it before we do a new release

This is a good idea!!

**Comment by philipphofmann** [comment]
Let's disable the required CI check and only merge the dependabot PRs when we want to. We still want to keep the dependabot PRs to remind us that there is a new version, because we should release the fastlane plugin every month or so with the updated sentry-cli version.
