### ISSUE TITLE
Option to control the log output

### ISSUE THREAD

**Issue by mojidabckuu** [getsentry/sentry-fastlane-plugin#244]
Currently there is a huge logging during the upload.
Is there a way to omit it or to stream into a file?

**Comment by philipphofmann** [comment]
When you call Fastlane from the command line, you can do something like 
```
fastlane [your_lane] > output.log
```

This should also work in CI.

**Comment by mojidabckuu** [comment]
Thank you @philipphofmann 

Unfortunately it is not my case because sentry action is the part of other lane. Stream `>` operator whole lane hides the output that we want to see in the web console.

Is there a plan what could be done to Helper during the cli call? May be pass a param to control the output.

**Comment by philipphofmann** [comment]
We set the log level to `debug` if you use verbose for Fastlane
https://github.com/getsentry/sentry-fastlane-plugin/blob/d36767725d0b21e85d27fc15058ad04315a0e726/lib/fastlane/plugin/sentry/helper/sentry_config.rb#L57

I think we should add a parameter for the log level `common_api_config_items`, so you can configure it.

**Comment by mojidabckuu** [comment]
@philipphofmann Are you sure?

https://github.com/getsentry/sentry-fastlane-plugin/blob/d36767725d0b21e85d27fc15058ad04315a0e726/lib/fastlane/plugin/sentry/helper/sentry_helper.rb#L38

Looking in this code it prints everything using `UI` which under the hood calls regular STDOUT flushing

**Comment by philipphofmann** [comment]
The helper should take the output from sentry-cli and forwards it to `UI`. The environment variable `SENTRY_LOG_LEVEL` is used by sentry-cli. If I'm not mistaken, we need to add an option the config, so you can simply configure it via Fastlane.

**Comment by kahest** [comment]
@denrase can you look into this?
