### ISSUE TITLE
Action 'sentry_debug_files_upload' not available in 1.19

### ISSUE THREAD

**Issue by oreporan** [getsentry/sentry-fastlane-plugin#245]
### Environment

What version are you running? Etc.
on 1.19.0

### Steps to Reproduce

1. run `fastlane run sentry_debug_files_upload`

### Expected Result
Start the CLI command

### Actual Result
` Action 'sentry_debug_files_upload' not available, run `fastlane actions` to get a full list`

**Comment by philipphofmann** [comment]
@oreporan, are you sure you pointing to 1.19.0? We made some changes with https://github.com/getsentry/sentry-fastlane-plugin/pull/234 that could be responsible for that, but they are only at the `master` branch and have not been released yet. If you target our `master` branch, https://github.com/getsentry/sentry-fastlane-plugin/pull/234 could be responsible for this.

**Comment by oreporan** [comment]
from fastlane cli

+---------------------------------------------------------------------------------------------------+
|                                           Used plugins                                            |
+---------------------------+---------+-------------------------------------------------------------+
| Plugin                    | Version | Action                                                      |
+---------------------------+---------+-------------------------------------------------------------+
| fastlane-plugin-appcenter | 2.1.2   | appcenter_codepush_release_react, appcenter_fetch_devices,  |
|                           |         | appcenter_fetch_version_number, appcenter_upload            |
| fastlane-plugin-sentry    | 1.19.0  | sentry_check_cli_installed, sentry_create_deploy,           |
|                           |         | sentry_create_release, sentry_finalize_release,             |
|                           |         | sentry_set_commits, sentry_upload_dif, sentry_upload_dsym,  |
|                           |         | sentry_upload_file, sentry_upload_proguard,                 |
|                           |         | sentry_upload_sourcemap                                     |

**Comment by bddq** [comment]
Same for me. Action not available in 1.19.0

**Comment by kahest** [comment]
`sentry_debug_files_upload` was recently added and will be first released with version `1.20.0`. It already shows up on the `README.md` on the `master` branch because the PR was already merged, but it's not available on version `1.19.0`.

If you use version `1.19.0` of the plugin, please refer to the [README.md for version `1.19.0`](https://github.com/getsentry/sentry-fastlane-plugin/blob/1.19.0/README.md) or alternatively wait for the release of `1.20.0`, which will be shipped soon.

**Comment by philipphofmann** [comment]
If the action is still unavailable with 1.20.0, please reopen this issue.
