### ISSUE TITLE
How to upload Android mapping.txt Proguard deobfuscation file?

### ISSUE THREAD

**Issue by GoodMirek** [getsentry/sentry-fastlane-plugin#28]
Hello,

We are using Fastlane to build Android project on our CI. Developers build releases for their testing manually. Using Gradle's sentry plugin for upload of mapping.txt is not practical, as it runs even when a developer runs the build and we want to upload the mapping.txt from CI only.

Is it possible to upload Android mapping.txt Proguard deobfuscation file to Sentry using this plugin?

**Comment by HazAT** [comment]
Not yet, but that's a good point.
We will start working on that.

**Comment by johnhaitas** [comment]
bump, has there been any progress on this?

**Comment by mpp-anasa** [comment]
@johnhaitas I created a fork of this plugin that achieves this: https://github.com/myPinPad/sentry-fastlane-plugin

To use it, just add 
`gem 'fastlane-plugin-sentry', git: "https://github.com/mypinpad/sentry-fastlane-plugin.git"`

to your Gemfile, and remove any dependency to `fastlane-plugin-sentry`

**Comment by Ghedeon** [comment]
Any updates in 2019?

**Comment by HazAT** [comment]
I merged the PR of @mpp-anasa now, will do a release today. Sorry for the delay here.
