### ISSUE TITLE
Could not find sourcemap at path 'main.jsbundle.map'

### ISSUE THREAD

**Issue by stereodenis** [getsentry/sentry-fastlane-plugin#281]
### Environment

"react-native": "0.75.4"
"@sentry/react-native": "5.35.0"

gem 'fastlane-plugin-sentry', '1.25.1'

### Steps to Reproduce

1. Creating source maps: `sh("cd ../..; npx react-native bundle --dev false --minify false --platform ios --entry-file index.js --reset-cache --bundle-output ios/fastlane/main.jsbundle --sourcemap-output ios/fastlane/main.jsbundle.map")`
2. Check existance: `sh("ls -la")`
![Image](https://github.com/user-attachments/assets/fba0fa17-cf13-4955-86e4-330ed92087a9)

3. Uploading by fastlane plugin:
```
sentry_upload_sourcemap(
      app_identifier: '***',
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG'],
      project_slug: ENV['SENTRY_PROJECT'],
      version: ENV['APP_VERSION_RAW'],
      build: ENV['APP_BUILD_VERSION_ANDROID'],
      sourcemap: 'main.jsbundle.map',
      rewrite: true
    )
```
### Expected Result

Source maps uploaded successfully 

### Actual Result

```
[13:26:27]: Called from Fastfile at line 30
[13:26:27]: ```
[13:26:27]:     28:	    sh("cd ..; ls -la")
[13:26:27]:     29:	    sh("cd ../..; ls -la")
[13:26:27]:  => 30:	    sentry_upload_sourcemap(
[13:26:27]:     31:	      app_identifier: '***',
[13:26:27]:     32:	      auth_token: ENV['SENTRY_AUTH_TOKEN'],
[13:26:27]: ```
[13:26:27]: Could not find sourcemap at path 'main.jsbundle.map'
```

**Comment by philipphofmann** [comment]
@stereodenis, you store the bundle and sourcemaps to the path `ios/fastlane/`. Can you please try changing the sourcemap input for the fastlane plugin from `main.jsbundle.map` to `ios/fastlane/main.jsbundle.map`? Maybe that fixes the problem.
