### ISSUE TITLE
Use sentry-cli installed with npm?

### ISSUE THREAD

**Issue by joshrlesch** [getsentry/sentry-fastlane-plugin#34]
Whats your thought on having an action option to pass in the path to the `sentry-cli`. Right now it is expecting you to install it with brew or `get-cli` bash script. But we already download the cli when `npm install` gets ran earlier in the CI process.

Are PR's welcome for something like this?

**Comment by HazAT** [comment]
Of course! Great idea :)
Feel free to submit a PR

**Comment by joshrlesch** [comment]
Working on this and wanted to make sure I didn't beak any tests. But on master, running `rspec` I get multiple failures. Should all tests being passing? Am I running them wrong?

**Comment by HazAT** [comment]
Oh sry, that's my bad, should have documented the tests.
Some of them are allowed to fail since they expect you to have `export SENTRY_PROPERTIES=` pointing to a valid properties file.

**Comment by philipphofmann** [comment]
Has been fixed with https://github.com/getsentry/sentry-fastlane-plugin/pull/97.
