### ISSUE TITLE
Is it possible to explicitly provide CFBundleShortVersionString and CFBundleVersion to Sentry?

### ISSUE THREAD

**Issue by bryanjclark** [getsentry/sentry-fastlane-plugin#36]
It’s neat that Sentry can parse an Info.plist file to find these two bits of info, but in the Khan Academy app, we use `.xconfig` file to hold the “source of truth” for these values, and what we have in our `Info.plist` are variables, e.g. `${APP_VERSION}` and `${BUILD_NUMBER}`.

I’d prefer it if Sentry’s Fastlane action could accept these values explicitly.

Currently, my workaround is to duplicate the `Info.plist` file, modify the values in the modified file, and upload that modified file instead of the standard `Info.plist`.

Would it be possible to do something like this? I’m happy to help if it’s a simple fix, but it looks (to me at least) like the `Info.plist` inspection is happening in Sentry’s servers, right?

**Comment by bryanjclark** [comment]
(It’s also 100% possible that I’m misunderstanding this! 😄)

One other thing I’m considering is explicitly pointing Sentry to the `Info.plist` inside our app’s `dSYM`.

**Comment by HazAT** [comment]
Hey, so this plugin is basically a wrapper around `sentry-cli`.
It forwards all parameters/commands to `sentry-cli`, that being said, would it help to pass in the version by manually from the `fastfile`?

Currently, we only provide `info-plist` param but we could also add `version` and `dist` to the command.
https://github.com/getsentry/sentry-fastlane-plugin/blob/master/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb

That would mean you need to be able to read the content of `.xconfig` in the `fastfile` in order to pass the correct version/build number.
Does this make sense?

**Comment by bryanjclark** [comment]
> would it help to pass in the version by manually from the fastfile?

Yeah, I think so! Here’s what I’m seeing in Sentry’s web UI:
<img width="1330" alt="screen shot 2018-05-03 at 12 40 47 pm" src="https://user-images.githubusercontent.com/868389/39599000-396515bc-4ecf-11e8-9024-2c6696e30b7e.png">

...those variables are all in our Info.plist file, and they’re populated at build time using `.xcconfig` files that we have, like `Release.xcconfig`, and `Common.xcconfig` which look a bit like this:
```
APP_VERSION = 4.9.0
BUILD_NUMBER = 31612
```

...we have `fastlane` setup to bump the build number on every release build, etc.

If there’s a way to explicitly provide these values to `sentry-cli` via the fastlane action, that’d be terrific, rather than the workaround I described above (duplicating Info.plist, modifying it, uploading that, and then deleting the modified Info.plist)

**Comment by bryanjclark** [comment]
Also, if there’s a way to delete these old faulty dSYMs from Sentry’s webapp, that’d be terrific. I posted a question in Sentry’s discussion forum:
https://forum.sentry.io/t/can-i-delete-dsyms-from-our-project/3722

(Also, it looks like there are other questions around deleting dSYMs there too but they haven’t been answered in a while, [like this one](https://forum.sentry.io/t/cleanup-of-old-dsyms/1939).)

**Comment by philipphofmann** [comment]
Hey @bryanjclark, 

this issue is almost 4 years old. Do you still need this feature? Did you find a workaround?

**Comment by brustolin** [comment]
We didn't hear anything about this for a while, closing the issue. Feel free to reopen it.
