### ISSUE TITLE
Sentry files minified

### ISSUE THREAD

**Issue by ribamarsantos** [getsentry/sentry-fastlane-plugin#47]
I'm uploading both bundle and and map files correctly. However when getting an error it's not showing the code but the minified one. Does anyone had a similar issue using RN ? For me seems to be a bug on lane. If this is not the right place to open it let me know please.

I had tried add url_prefix but seems not necessary cause I still get the same error. 

Here is how my artifacts ends when uploaded:
![Captura de Tela 2019-05-29 às 5 48 26 PM](https://user-images.githubusercontent.com/12488166/58596733-d254d600-823a-11e9-9a83-65a119e2f15f.png)

Here is how I get the errors on Sentry:
![Captura de Tela 2019-05-29 às 5 49 33 PM](https://user-images.githubusercontent.com/12488166/58596745-e1d41f00-823a-11e9-8b0e-17947a94e683.png)

**Comment by ribamarsantos** [comment]
Problem fixed. I was missing the file_url parameter.

**Comment by christhegrand** [comment]
I'm having the same issue. What did you set for file_url to fix this?
