### ISSUE TITLE
Add parameter for app_identifier to sentry_upload_dsym

### ISSUE THREAD

**Issue by JensLeirens** [getsentry/sentry-fastlane-plugin#55]
Hi all, 

When using the sentry_upload_dsym function of fastlane i cannot specify the app_identifier that the command has to take. Now it just only takes the first one it already had. 

My case: I have multiple targets in one project, those targets all have a different app_identifier.  I want to upload the symbols for each target with a fastlane command

My current code inside my fastlane command
```
 sentry_upload_dsym(
            auth_token: 'token',
            org_slug: 'org-slug',
            project_slug: 'baseProject-slug'
        )
```

**Comment by philipphofmann** [comment]
You don't need to specify an app identifier. If you have multiple apps in the same project, you can upload different dSYMs of different apps to the same project, and Sentry will do the rest for you.
