### ISSUE TITLE
Url for self hosted Sentry?

### ISSUE THREAD

**Issue by Karmadon** [getsentry/sentry-fastlane-plugin#56]
How can I set url for self hosted sentry server

**Comment by tsfischer** [comment]
I am also looking for how to do this. I was `using upload_symbols_to_sentry` but it says it is deprecated and I should use this plugin instead. However I see nothing about self-hosting.

**Comment by tsfischer** [comment]
OK I figured it out. Add the following line to your Fastfile, before your sentry calls:

`ENV["SENTRY_URL"] = "https://path.to.your.sentry.instance/"`

Would be nice if they would have supported the URL parameter like the old method did.

**Comment by dirtyhenry** [comment]
Using `url` also seems to be working:

```
    sentry_upload_dsym(
      url: "https://sentry.foo.tld",
      auth_token: ...
      org_slug: ...
      project_slug: ...
    )
```

**Comment by philipphofmann** [comment]
@dirtyhenry opened a PR to update this in our docs: https://github.com/getsentry/sentry-docs/pull/2704. I'm going to close this now.
