### ISSUE TITLE
Version parameter escaped in sentry_upload_sourcemap but not in sentry_upload_file

### ISSUE THREAD

**Issue by rgommezz** [getsentry/sentry-fastlane-plugin#57]
I have some ad-hoc code on our CI to manually create Sentry releases using Fastlane.

It's a React Native application, so the code takes care of uploading the bundle file, as well as the sourcemaps.

Interestingly, I've found out that [`upload_file`](https://github.com/getsentry/sentry-fastlane-plugin/blob/master/lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb#L19) treats the version string as it is passed, but [`upload_sourcemap`](https://github.com/getsentry/sentry-fastlane-plugin/blob/master/lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb#L19) escapes the string provided, so it feels there is some inconsistency there. Is the escaping needed? Could it be removed?

My `version` name contains special characters like `+`, so I can't match the `version` because when executing `upload_sourcemaps`, the escaping will prepend a backlash on every special characters, for example with the 'plus' character: ` + => \+ `. 

It would be great to remove the escaping if it doesn't arise any security concerns.

**Comment by WinstonKamau** [comment]
Facing the same issue. `sentry_upload_sourcemap` would be deployed to release version `0.8.0\ \(4.1855.1.34.0\)` and `sentry_upload_file` would deploy to release`0.8.0 (4.1855.1.34.0)`, creating two releases on Sentry

**Comment by dantereve** [comment]
Hi guys, I'm facing the same issue where `sentry_upload_sourcemap` creates a new release with an escaped name. 

I'm passing `com.xxxxx.student.staging@1.12.6+129` to both `sentry_upload_sourcemap` and `sentry_upload_file`. 

Here is a screenshot : 

<img width="202" alt="Screenshot 2020-07-17 at 17 41 37" src="https://user-images.githubusercontent.com/13101343/87805019-fca98e80-c854-11ea-81f5-297a82acf639.png">
