### ISSUE TITLE
Is there a need to specify the environment when uploading dsyms?

### ISSUE THREAD

**Issue by alex-benoit** [getsentry/sentry-fastlane-plugin#58]
What is the best practice for ios native error handling, given a staging and production build? Would Sentry get confused when uploading the same version/build number combo for different configurations/schemes? Do we need different projects? Ideally, we would only have on project with different environments, but I am worried about the dsym handling in this case.

**Comment by philipphofmann** [comment]
@alex-benoit, I guess you already figured it out. Sentry doesn't get confused when uploading the same version/build number combo for different configurations/schemes. You don't need different projects. I would recommend using the same project with different environments for staging, debug, and production.
