### ISSUE TITLE
Option to pass `--include-sources` to sentry-cli?

### ISSUE THREAD

**Issue by tmm1** [getsentry/sentry-fastlane-plugin#59]
The android sentry integration (https://docs.sentry.io/platforms/android/) offers a `includeNativeSources true` option which invokes `sentry-cli` with `--include-sources`.

Is there something similar available in this fastlane plugin?

**Comment by ainopara** [comment]
Adding this option enable iOS developers to upload sourcebundle to sentry with fastlane. 
Please consider adding this option to `sentry_upload_dsym` action.

**Comment by lhunath** [comment]
This issue is addressed by https://github.com/getsentry/sentry-fastlane-plugin/pull/89, however it appears the syntax for the options passed to `sentry-cli` is incorrectly using underscores instead of dashes. /cc @denrase

**Comment by denrase** [comment]
@ainopara Like @lhunath correctly mentioned, this is present but incorrectly used. Hope to have this resolved in a short while.

**Comment by bruno-garcia** [comment]
Sounds good. I'll add a `up-for-grabs` hoping now during Hacktoberfest someone helps us out here

**Comment by lhunath** [comment]
This is already addressed by https://github.com/getsentry/sentry-fastlane-plugin/pull/96

**Comment by bruno-garcia** [comment]
Thanks @lhunath. The only concern I have with that change was on this [one comment](https://github.com/getsentry/sentry-fastlane-plugin/pull/96#discussion_r706527290):

> Would it be possible to have sentry_upload_dsym simply forward the call to sentry_upload_dif to avoid the breaking change? Not sure it's worth creating friction with customers that have set this up 5 years ago and have no problems

**Comment by lhunath** [comment]
Yup; if you'd like, you can ask me in #96 to either revert the removal of upload_dsym or propose some alternative transition strategy.
