### ISSUE TITLE
Use sentry.properties?

### ISSUE THREAD

**Issue by liamjones** [getsentry/sentry-fastlane-plugin#69]
Is there no option to make use of sentry.properties to work out auth token, org, etc when calling sentry_upload_dsym, etc?

**Comment by dkarter** [comment]
Can be done with 'fastlane-plugin-property_file_read' plugin:

```ruby

    # read sentry config from sentry.properties
    sentry_config = property_file_read(file: "sentry.properties")

    # upload the downloaded dSYMs to sentry
    sentry_upload_dsym(
      auth_token: sentry_config["auth.token"],
      org_slug: sentry_config["defaults.org"],
      project_slug: sentry_config["defaults.project"],
    )
```

**Comment by liamjones** [comment]
Yeah, that's what I'm doing atm (with fastlane-plugin-properties but it's essentially the same).

**Comment by carlosen14** [comment]
why `property_file_read`can't read the url? it just trim it to `https:`and the rest is ignored

**Comment by liamjones** [comment]
@carlosen14 because, as far as I'm aware, it's for reading local files, not remote ones. You'd need to download a remote file first, then when it's on the local filesystem you'd be able to use `property_file_read` with it.

**Comment by carlosen14** [comment]
Sorry i didn't explain well, I was trying to read the property defaults.url, but the value read was just `https:`(that's all), but I already figured out,  I tried **dkarter** example:

```rb
    # read sentry config from sentry.properties
    sentry_config = property_file_read(file: "sentry.properties")

    # upload the downloaded dSYMs to sentry
    sentry_upload_dsym(
      auth_token: sentry_config[:"auth.token"], # << but every property needs the semi-colon before the string key 
                                ^
      org_slug: sentry_config["defaults.org"],
      project_slug: sentry_config["defaults.project"],
    )
```

**Comment by philipphofmann** [comment]
As you can use `property_file_read`, we can close this issue.
