### ISSUE TITLE
fastlane plugin release name format

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-fastlane-plugin#71]
fastlane creates upload like this e.g.:

`com.yourcompany.customer-5be699c8d6299257ccaac9da064ffa895d01fce8`

creates while in the event that has been sent to Sentry it looks different.

The goal is to align the fastlane plugin with what we actually send, also eventually adding the option to be able to define dist

Here you can see that the release has the wrong format, this has to be aligned with what our SDKs send. (Also add dist as an argument)
https://github.com/getsentry/sentry-fastlane-plugin/blob/master/lib/fastlane/plugin/sentry/actions/sentry_create_release.rb#L11

More context on: https://app.asana.com/0/1163978839534255/1199538243515764

**Comment by borninla** [comment]
#72
