### ISSUE TITLE
How to upload to self hosted sentry?

### ISSUE THREAD

**Issue by amadeu01** [getsentry/sentry-fastlane-plugin#73]
How can I pass the api host?

**Comment by kamui545** [comment]
Check this: https://github.com/getsentry/sentry-fastlane-plugin/issues/56

I am gonna try as well

**Comment by denrase** [comment]
@kamui545 @amadeu01 Providing `url` param did work for both of you?

**Comment by kamui545** [comment]
I did not have time to try out yet, however, I found out that the doc website seems to be more updated / complete than the readme.

Using `api_host` should work.

https://docs.fastlane.tools/actions/upload_symbols_to_sentry/

**Comment by denrase** [comment]
You should be able to provide `url` parameter to `sentry_upload_dif`, as well as all other actions. The doc seems to be outdated regarding `upload_symbols_to_sentry `, this is not available anymore. 

https://github.com/getsentry/sentry-fastlane-plugin/blob/eec745767a2e6e0f9c50583c23f8d235ac110842/lib/fastlane/plugin/sentry/helper/sentry_config.rb#L6

**Comment by denrase** [comment]
Closing for now.
