### ISSUE TITLE
Add support for build number for releases

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-fastlane-plugin#84]
The plugin currently sets the version for a release with `app_identifier@version`. sentry-cli also supports [`build-number`](https://docs.sentry.io/product/cli/releases/#creating-releases), which the plugin currently doesn't support.

This came up in https://github.com/getsentry/sentry-fastlane-plugin/pull/83#discussion_r647218801

**Comment by bruno-garcia** [comment]
Makes sense. Releases wouldn't match based on the value sent by the SDK and the release created with the plugin.
So this is rather important.

Here's what the SDK does and the values are supposed to match:

https://github.com/getsentry/sentry-cocoa/blob/3c44b95d68af7b9d0c0ba8c794c59d1bcd3da1f8/Sources/Sentry/SentryOptions.m#L78-L79
