### ISSUE TITLE
Add support for upload-dif

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-fastlane-plugin#86]
The Fastlane plugin currently only supports `upload-dsym` of `sentry-cli`. The new up-to-date way is to use `upload-dif` instead. We can add an extra action called `sentry_upload_dif` and keep the old action `sentry_upload_dsym` for backward compatibility.

**Comment by bruno-garcia** [comment]
Good catch. We should document this too on docs.sentry.io

**Comment by flub** [comment]
We're writing docs for appstore connect this week, i guess we'll initially document the workaround in https://github.com/getsentry/sentry-cocoa/blob/f36974719600967d79afb6f27826d37cf5ceaf7e/fastlane/Fastfile#L92-L101
